version: '3'
services:
  ubuntu_desktop:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ubuntu_test_container
    image: biwashi/ubuntu-test-container
    tty: true
    volumes:
      - ./workspace/:/home/new/workspace
    ports:
      - "8080:8080"